# Generated by Django 5.0.3 on 2024-03-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEnlisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30)),
                ('orderid', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=40)),
                ('time', models.TimeField()),
                ('incentive', models.IntegerField()),
            ],
        ),
    ]
